items:
- draw_count: 抽数
- wuxiang_point: 无相积分
- random_limited_skin: 随机限定皮肤礼
- random_legendary_skin: 随机传说皮肤
- random_skin: 随机皮肤礼
- skin_fragment8: 皮肤碎片8
- xiaozhoujimeng2: 小舟寄梦2
- sunwukong_wuxiang: 孙悟空_无相
- yao_zhenwohezi: 瑶_真我赫兹
- zhenji_xuejingqiyu: 甄姬_雪境奇遇
- xuejingqiyuquanpingtianmu: 雪境奇遇全屏天幕
- xiaoqiao_shanhailinlangsheng: 小乔_山海琳琅生
- zhaoyun_longdan: 赵云_龙胆
- daji_reqingsangba: 妲己_热情桑巴
- epic_skin: 史诗皮肤
- brave_skin: 勇者皮肤
- companion_skin: 伴生皮肤
pools:
- begin_pool:
  - probability: 0.004
    actions: random_limited_skin += 1
  - probability: 0.005
    actions: random_legendary_skin += 1
  - probability: 0.135
    actions: random_skin += 1
  - probability: 0.008
    actions: wuxiang_point += 68
  - probability: 0.04
    actions: wuxiang_point += 28
  - probability: 0.237
    actions: wuxiang_point += 18
  - probability: 0.3
    actions: wuxiang_point += 8
  - probability: 0.15
    actions: skin_fragment8 += 1
  - probability: 0.121
    actions: xiaozhoujimeng2 += 1
- random_limited_skin_pool:
  - probability: 0.0034
    actions: sunwukong_wuxiang += 1
  - probability: 0.0033
    actions: yao_zhenwohezi += 1
  - probability: 0.0033
    actions: zhenji_xuejingqiyu += 1
  - probability: 0.01
    actions: xuejingqiyuquanpingtianmu += 1
  - probability: 0.32
    actions: xiaoqiao_shanhailinlangsheng += 1
  - probability: 0.33
    actions: zhaoyun_longdan += 1
  - probability: 0.33
    actions: daji_reqingsangba += 1
- random_skin_pool:
  - probability: 0.1
    actions: epic_skin += 1
  - probability: 0.3
    actions: brave_skin += 1
  - probability: 0.6
    actions: companion_skin += 1
rules:
- draw_5:
    mode: once
    condition:
      check: draw_count >= 5
      actions:
      - random_skin += 1
- draw_10:
    mode: once
    condition:
      check: draw_count >= 10
      actions:
      - random_skin += 1
- draw_25:
    mode: once
    condition:
      check: draw_count >= 25
      actions:
      - random_skin += 1
- draw_40:
    mode: once
    condition:
      check: draw_count >= 40
      actions:
      - wuxiang_point += 288
- draw_45:
    mode: once
    condition:
      check: draw_count >= 45
      actions:
      - random_skin += 1
- draw_50:
    mode: once
    condition:
      check: draw_count >= 50
      actions:
      - random_skin += 1
- draw_65:
    mode: once
    condition:
      check: draw_count >= 65
      actions:
      - random_skin += 1
- draw_80:
    mode: once
    condition:
      check: draw_count >= 80
      actions:
      - wuxiang_point += 288
- draw_85:
    mode: once
    condition:
      check: draw_count >= 85
      actions:
      - random_skin += 1
- draw_90:
    mode: once
    condition:
      check: draw_count >= 90
      actions:
      - random_skin += 1
- draw_105:
    mode: once
    condition:
      check: draw_count >= 105
      actions:
      - random_skin += 1
- draw_120:
    mode: once
    condition:
      check: draw_count >= 120
      actions:
      - wuxiang_point += 288
item_resolve:
- item: random_limited_skin
  retain: 0
  actions:
  - random_limited_skin -= 1
  - draw random_limited_skin_pool
- item: random_legendary_skin
  retain: 0
  actions:
  - random_legendary_skin -= 1
  - wuxiang_point += 120
- item: random_skin
  retain: 0
  actions:
  - random_skin -= 1
  - draw random_skin_pool
- item: skin_fragment8
  retain: 0
  actions:
  - skin_fragment8 -= 1
  - wuxiang_point += 5
- item: xiaozhoujimeng2
  retain: 0
  actions:
  - xiaozhoujimeng2 -= 1
  - wuxiang_point += 5
- item: sunwukong_wuxiang
  retain: 0
  actions:
  - sunwukong_wuxiang -= 1
  - wuxiang_point += 288
- item: yao_zhenwohezi
  retain: 0
  actions:
  - yao_zhenwohezi -= 1
  - wuxiang_point += 288
- item: zhenji_xuejingqiyu
  retain: 0
  actions:
  - zhenji_xuejingqiyu -= 1
  - wuxiang_point += 288
- item: xuejingqiyuquanpingtianmu
  retain: 0
  actions:
  - xuejingqiyuquanpingtianmu -= 1
  - wuxiang_point += 288
- item: xiaoqiao_shanhailinlangsheng
  retain: 0
  actions:
  - xiaoqiao_shanhailinlangsheng -= 1
  - wuxiang_point += 288
- item: zhaoyun_longdan
  retain: 0
  actions:
  - zhaoyun_longdan -= 1
  - wuxiang_point += 288
- item: daji_reqingsangba
  retain: 0
  actions:
  - daji_reqingsangba -= 1
  - wuxiang_point += 288
- item: epic_skin
  retain: 0
  actions:
  - epic_skin -= 1
  - wuxiang_point += 60
- item: brave_skin
  retain: 0
  actions:
  - brave_skin -= 1
  - wuxiang_point += 40
- item: companion_skin
  retain: 0
  actions:
  - companion_skin -= 1
  - wuxiang_point += 20
initial:
- change begin_pool
schema_version: 2
every_draw:
- draw_count += 1
