items:
- draw_count: 抽数
- sanliouduihuanbi: 三丽鸥兑换币
- teshuhuizhangbaodijishu: 特殊徽章保底计数
- teshuhuizhang1: 特殊徽章1
- teshuhuizhang2: 特殊徽章2
- teshuhuizhang3: 特殊徽章3
- teshuhuizhang4: 特殊徽章4
- yao_daergouzhimeng: 瑶_大耳狗之梦
- anqila_kuluomizhixin: 安琪拉_酷洛米之心
- mianhuatangjuhuitianmu: 棉花糖聚会天幕
- lingbaozhuangban_kaidimaodetongqu: 灵宝装扮_凯蒂猫的童趣
- lingbaozhuangban_kuluomidewanpi: 灵宝装扮_酷洛米的顽皮
- lingbaozhuangban_meiledidelingli: 灵宝装扮_美乐蒂的伶俐
- lingbaozhuangban_daergoudenuannuan: 灵宝装扮_大耳狗的温暖
- lingbaozhuangban_budinggoudeyouxian: 灵宝装扮_布丁狗的悠闲
- jifenduobaodiyongquan: 积分夺宝抵用券
- pifusuipian: 皮肤碎片
- dianbotonpinqinmidudaoju: 电波同频亲密度道具
- gexingchuochuodaergouzhimeng: 个性戳戳大耳狗之梦
pools:
- begin_pool:
  - probability: 0.001
    actions: yao_daergouzhimeng += 1
  - probability: 0.001
    actions: anqila_kuluomizhixin += 1
  - probability: 0.001
    actions: mianhuatangjuhuitianmu += 1
  - probability: 0.368
    actions: sanliouduihuanbi += 6
  - probability: 0.19
    actions: sanliouduihuanbi += 16
  - probability: 0.074
    actions: sanliouduihuanbi += 26
  - probability: 0.002
    actions: sanliouduihuanbi += 66
  - probability: 0.08
    actions: jifenduobaodiyongquan += 1
  - probability: 0.08
    actions: pifusuipian += 6
  - probability: 0.1
    actions: dianbotonpinqinmidudaoju += 2
  - probability: 0.1
    actions: gexingchuochuodaergouzhimeng += 4
  - probability: 0.0006
    actions: lingbaozhuangban_kaidimaodetongqu += 1
  - probability: 0.0006
    actions: lingbaozhuangban_kuluomidewanpi += 1
  - probability: 0.0006
    actions: lingbaozhuangban_meiledidelingli += 1
  - probability: 0.0006
    actions: lingbaozhuangban_daergoudenuannuan += 1
  - probability: 0.0006
    actions: lingbaozhuangban_budinggoudeyouxian += 1
- teshuhuizhang1_pool:
  - probability: 1
    actions: teshuhuizhang1 += 1
- teshuhuizhang2_pool:
  - probability: 0.5
    actions: teshuhuizhang2 += 1
  - probability: 0.5
- teshuhuizhang3_pool:
  - probability: 0.25
    actions: teshuhuizhang3 += 1
  - probability: 0.75
- teshuhuizhang4_pool:
  - probability: 0.1
    actions: teshuhuizhang4 += 1
  - probability: 0.9
- teshuhuizhang_pool:
  - probability: 0.32
    actions: sanliouduihuanbi += 28
  - probability: 0.3
    actions: sanliouduihuanbi += 48
  - probability: 0.34
    actions: sanliouduihuanbi += 88
  - probability: 0.035
    actions: sanliouduihuanbi += 168
  - probability: 0.005
    actions: sanliouduihuanbi += 198
every_draw:
- draw_count += 1
- teshuhuizhangbaodijishu += 1
rules:
- teshuhuizhang_gain:
    mode: per_draw
    condition:
      op: OR
      children:
      - op: AND
        children:
        - check: teshuhuizhangbaodijishu < 10
        - check: teshuhuizhang1 == 0
        - check: teshuhuizhang2 == 0
        - check: teshuhuizhang3 == 0
        - check: teshuhuizhang4 == 0
        actions:
        - draw teshuhuizhang1_pool
      - op: AND
        children:
        - check: teshuhuizhangbaodijishu < 10
        - check: teshuhuizhang1 == 1
        - check: teshuhuizhang2 == 0
        - check: teshuhuizhang3 == 0
        - check: teshuhuizhang4 == 0
        actions:
        - draw teshuhuizhang2_pool
      - op: AND
        children:
        - check: teshuhuizhangbaodijishu < 10
        - check: teshuhuizhang1 == 1
        - check: teshuhuizhang2 == 1
        - check: teshuhuizhang3 == 0
        - check: teshuhuizhang4 == 0
        actions:
        - draw teshuhuizhang3_pool
      - op: AND
        children:
        - check: teshuhuizhangbaodijishu < 10
        - check: teshuhuizhang1 == 1
        - check: teshuhuizhang2 == 1
        - check: teshuhuizhang3 == 1
        - check: teshuhuizhang4 == 0
        actions:
        - draw teshuhuizhang4_pool
- teshuhuizhangbaodi_execute:
    mode: per_draw
    condition:
      check: teshuhuizhangbaodijishu == 10
      actions:
      - teshuhuizhang1 = 1
      - teshuhuizhang2 = 1
      - teshuhuizhang3 = 1
      - teshuhuizhang4 = 1
      - teshuhuizhangbaodijishu = 0
- teshuhuizhang_execute:
    mode: per_draw
    condition:
      op: AND
      children:
      - check: teshuhuizhang1 == 1
      - check: teshuhuizhang2 == 1
      - check: teshuhuizhang3 == 1
      - check: teshuhuizhang4 == 1
      actions:
      - teshuhuizhang1 = 0
      - teshuhuizhang2 = 0
      - teshuhuizhang3 = 0
      - teshuhuizhang4 = 0
      - teshuhuizhangbaodijishu = 0
      - draw teshuhuizhang_pool
item_resolve:
- item: yao_daergouzhimeng
  retain: 1
  actions:
  - yao_daergouzhimeng -= 1
  - sanliouduihuanbi += 198
- item: anqila_kuluomizhixin
  retain: 1
  actions:
  - anqila_kuluomizhixin -= 1
  - sanliouduihuanbi += 198
- item: mianhuatangjuhuitianmu
  retain: 1
  actions:
  - mianhuatangjuhuitianmu -= 1
  - sanliouduihuanbi += 168
- item: lingbaozhuangban_kaidimaodetongqu
  retain: 1
  actions:
  - lingbaozhuangban_kaidimaodetongqu -= 1
  - sanliouduihuanbi += 98
- item: lingbaozhuangban_kuluomidewanpi
  retain: 1
  actions:
  - lingbaozhuangban_kuluomidewanpi -= 1
  - sanliouduihuanbi += 98
- item: lingbaozhuangban_meiledidelingli
  retain: 1
  actions:
  - lingbaozhuangban_meiledidelingli -= 1
  - sanliouduihuanbi += 98
- item: lingbaozhuangban_daergoudenuannuan
  retain: 1
  actions:
  - lingbaozhuangban_daergoudenuannuan -= 1
  - sanliouduihuanbi += 98
- item: lingbaozhuangban_budinggoudeyouxian
  retain: 1
  actions:
  - lingbaozhuangban_budinggoudeyouxian -= 1
  - sanliouduihuanbi += 98
initial:
- change begin_pool
schema_version: 2
