retained_items:
- yao_daergouzhimeng: 1
- sanliouduihuanbi: 465
termination_rule:
  condition:
    op: OR
    children:
    - check: yao_daergouzhimeng >= 1
      actions: terminate 抽中皮肤
    - check: sanliouduihuanbi >= 465
      actions: terminate 兑换币兑换
