retained_items:
- yao_daergouzhimeng: 1
- sanliouduihuanbi: 498
termination_rule:
  condition:
    op: OR
    children:
    - check: yao_daergouzhimeng >= 1
      actions: terminate 抽中皮肤
    - check: sanliouduihuanbi >= 498
      actions: terminate 兑换币兑换
