items:
- draw_count: 抽数
- jianxinling: 剑心令
- random_limited_skin: 随机限定皮肤礼
- random_legendary_skin: 随机传说皮肤
- random_skin: 随机皮肤礼
- skin_fragment8: 皮肤碎片8
- yanyuhuadie2: 烟雨化蝶2
- lixin_wenxinjian: 李信_问心剑
- gongsunli_lihenyan: 公孙离_离恨烟
- yao_qilingchilongjian: 耀_器灵螭龙剑
- moranjianghutianmu: 墨染江湖天幕
- bailixuance_baihuzhi: 百里玄策_白虎志
- sunwukong_qitiandasheng: 孙悟空_齐天大圣
- sunshangxiang_yijielingqi: 孙尚香_异界灵契
- wangzhaojun_xingqiongzhisheng: 王昭君_星穹之声
- libai_fengqiuhuang: 李白_凤求凰
- epic_skin: 史诗皮肤
- brave_skin: 勇者皮肤
- companion_skin: 伴生皮肤
pools:
- begin_pool:
  - probability: 0.004
    actions: random_limited_skin += 1
  - probability: 0.005
    actions: random_legendary_skin += 1
  - probability: 0.135
    actions: random_skin += 1
  - probability: 0.008
    actions: jianxinling += 68
  - probability: 0.04
    actions: jianxinling += 28
  - probability: 0.237
    actions: jianxinling += 18
  - probability: 0.3
    actions: jianxinling += 8
  - probability: 0.15
    actions: skin_fragment8 += 1
  - probability: 0.121
    actions: yanyuhuadie2 += 1
- random_limited_skin_pool:
  - probability: 0.0034
    actions: lixin_wenxinjian += 1
  - probability: 0.0033
    actions: gongsunli_lihenyan += 1
  - probability: 0.0033
    actions: yao_qilingchilongjian += 1
  - probability: 0.01
    actions: moranjianghutianmu += 1
  - probability: 0.162
    actions: bailixuance_baihuzhi += 1
  - probability: 0.162
    actions: sunwukong_qitiandasheng += 1
  - probability: 0.162
    actions: sunshangxiang_yijielingqi += 1
  - probability: 0.162
    actions: wangzhaojun_xingqiongzhisheng += 1
  - probability: 0.162
    actions: libai_fengqiuhuang += 1
  - probability: 0.17
    actions: jianxinling += 288
- random_skin_pool:
  - probability: 0.1
    actions: epic_skin += 1
  - probability: 0.3
    actions: brave_skin += 1
  - probability: 0.6
    actions: companion_skin += 1
rules:
- draw_5:
    mode: once
    condition:
      check: draw_count >= 5
      actions:
      - random_skin += 1
- draw_10:
    mode: once
    condition:
      check: draw_count >= 10
      actions:
      - random_skin += 1
- draw_25:
    mode: once
    condition:
      check: draw_count >= 25
      actions:
      - random_skin += 1
- draw_40:
    mode: once
    condition:
      check: draw_count >= 40
      actions:
      - jianxinling += 288
- draw_45:
    mode: once
    condition:
      check: draw_count >= 45
      actions:
      - random_skin += 1
- draw_50:
    mode: once
    condition:
      check: draw_count >= 50
      actions:
      - random_skin += 1
- draw_65:
    mode: once
    condition:
      check: draw_count >= 65
      actions:
      - random_skin += 1
- draw_80:
    mode: once
    condition:
      check: draw_count >= 80
      actions:
      - jianxinling += 288
- draw_85:
    mode: once
    condition:
      check: draw_count >= 85
      actions:
      - random_skin += 1
- draw_90:
    mode: once
    condition:
      check: draw_count >= 90
      actions:
      - random_skin += 1
- draw_105:
    mode: once
    condition:
      check: draw_count >= 105
      actions:
      - random_skin += 1
- draw_120:
    mode: once
    condition:
      check: draw_count >= 120
      actions:
      - jianxinling += 288
- draw_125:
    mode: once
    condition:
      check: draw_count >= 125
      actions:
      - random_skin += 1
- draw_130:
    mode: once
    condition:
      check: draw_count >= 130
      actions:
      - random_skin += 1
- draw_145:
    mode: once
    condition:
      check: draw_count >= 145
      actions:
      - random_skin += 1
- draw_160:
    mode: once
    condition:
      check: draw_count >= 160
      actions:
      - random_skin += 1
item_resolve:
- item: random_limited_skin
  retain: 0
  actions:
  - random_limited_skin -= 1
  - draw random_limited_skin_pool
- item: random_legendary_skin
  retain: 0
  actions:
  - random_legendary_skin -= 1
  - jianxinling += 120
- item: random_skin
  retain: 0
  actions:
  - random_skin -= 1
  - draw random_skin_pool
- item: skin_fragment8
  retain: 0
  actions:
  - skin_fragment8 -= 1
  - jianxinling += 5
- item: yanyuhuadie2
  retain: 0
  actions:
  - yanyuhuadie2 -= 1
  - jianxinling += 5
- item: lixin_wenxinjian
  retain: 0
  actions:
  - lixin_wenxinjian -= 1
  - jianxinling += 288
- item: gongsunli_lihenyan
  retain: 0
  actions:
  - gongsunli_lihenyan -= 1
  - jianxinling += 288
- item: yao_qilingchilongjian
  retain: 0
  actions:
  - yao_qilingchilongjian -= 1
  - jianxinling += 288
- item: moranjianghutianmu
  retain: 0
  actions:
  - moranjianghutianmu -= 1
  - jianxinling += 288
- item: bailixuance_baihuzhi
  retain: 0
  actions:
  - bailixuance_baihuzhi -= 1
  - jianxinling += 288
- item: sunwukong_qitiandasheng
  retain: 0
  actions:
  - sunwukong_qitiandasheng -= 1
  - jianxinling += 288
- item: sunshangxiang_yijielingqi
  retain: 0
  actions:
  - sunshangxiang_yijielingqi -= 1
  - jianxinling += 288
- item: wangzhaojun_xingqiongzhisheng
  retain: 0
  actions:
  - wangzhaojun_xingqiongzhisheng -= 1
  - jianxinling += 288
- item: libai_fengqiuhuang
  retain: 0
  actions:
  - libai_fengqiuhuang -= 1
  - jianxinling += 288
- item: epic_skin
  retain: 0
  actions:
  - epic_skin -= 1
  - jianxinling += 60
- item: brave_skin
  retain: 0
  actions:
  - brave_skin -= 1
  - jianxinling += 40
- item: companion_skin
  retain: 0
  actions:
  - companion_skin -= 1
  - jianxinling += 20
initial:
- change begin_pool
schema_version: 2
every_draw:
- draw_count += 1
