retained_items:
- lixin_wenxinjian: 1
- jianxinling: 998
termination_rule:
  condition:
    op: OR
    children:
    - check: lixin_wenxinjian >= 1
      actions: terminate skin obtained
    - check: jianxinling >= 998
      actions: terminate point exchange
