retained_items:
- lixin_wenxinjian: 1
- gongsunli_lihenyan: 1
- yao_qilingchilongjian: 1
- jianxinling: 998
termination_rule:
  condition:
    op: OR
    children:
    - check: lixin_wenxinjian >= 1
      actions: terminate skin obtained
    - check: gongsunli_lihenyan >= 1
      actions: terminate skin obtained
    - check: yao_qilingchilongjian >= 1
      actions: terminate skin obtained
    - check: jianxinling >= 998
      actions: terminate point exchange
