retained_items:
- lixin_wenxinjian: 1
- jianxinling: 1831
termination_rule:
  condition:
    op: OR
    children:
    - op: AND
      children:
      - check: lixin_wenxinjian >= 1
      - check: jianxinling >= 833
      actions: terminate skin obtained
    - check: jianxinling >= 1831
      actions: terminate point exchange
