items:
- draw_count: 抽数
- nezha2duihuanbi: 哪吒2兑换币
- teshuhuizhangbaodijishu: 特殊徽章保底计数
- teshuhuizhang1: 特殊徽章1
- teshuhuizhang2: 特殊徽章2
- teshuhuizhang3: 特殊徽章3
- teshuhuizhang4: 特殊徽章4
- kai_donghailongwang_aoguang: 铠_东海龙王_敖光
- miyue_xihailongwang_aorun: 芈月_西海龙王_敖闰
- talangtongxintianmu: 踏浪同心天幕
- yijianhuiyoutianmu: 以毽会友天幕
- jifenduobaodiyongquan: 积分夺宝抵用券
- pifusuipian: 皮肤碎片
- weinizhaixingqinmidudaoju: 为你摘星亲密度道具
- gexingchuochuoyijianhuiyou: 个性戳戳以毽会友
pools:
- begin_pool:
  - probability: 0.001
    actions: kai_donghailongwang_aoguang += 1
  - probability: 0.001
    actions: miyue_xihailongwang_aorun += 1
  - probability: 0.001
    actions: talangtongxintianmu += 1
  - probability: 0.001
    actions: yijianhuiyoutianmu += 1
  - probability: 0.368
    actions: nezha2duihuanbi += 6
  - probability: 0.19
    actions: nezha2duihuanbi += 16
  - probability: 0.074
    actions: nezha2duihuanbi += 26
  - probability: 0.002
    actions: nezha2duihuanbi += 66
  - probability: 0.08
    actions: jifenduobaodiyongquan += 1
  - probability: 0.08
    actions: pifusuipian += 6
  - probability: 0.102
    actions: weinizhaixingqinmidudaoju += 2
  - probability: 0.1
    actions: gexingchuochuoyijianhuiyou += 2
- teshuhuizhang1_pool:
  - probability: 1
    actions: teshuhuizhang1 += 1
- teshuhuizhang2_pool:
  - probability: 0.5
    actions: teshuhuizhang2 += 1
  - probability: 0.5
- teshuhuizhang3_pool:
  - probability: 0.25
    actions: teshuhuizhang3 += 1
  - probability: 0.75
- teshuhuizhang4_pool:
  - probability: 0.1
    actions: teshuhuizhang4 += 1
  - probability: 0.9
- teshuhuizhang_pool:
  - probability: 0.32
    actions: nezha2duihuanbi += 28
  - probability: 0.3
    actions: nezha2duihuanbi += 48
  - probability: 0.34
    actions: nezha2duihuanbi += 88
  - probability: 0.035
    actions: nezha2duihuanbi += 168
  - probability: 0.005
    actions: nezha2duihuanbi += 198
rules:
- teshuhuizhangbaodi:
    mode: per_draw
    condition:
      check: draw_count >= 1
      actions:
      - teshuhuizhangbaodijishu += 1
- teshuhuizhang_gain:
    mode: per_draw
    condition:
      op: OR
      children:
      - op: AND
        children:
        - check: teshuhuizhangbaodijishu < 10
        - check: teshuhuizhang1 == 0
        - check: teshuhuizhang2 == 0
        - check: teshuhuizhang3 == 0
        - check: teshuhuizhang4 == 0
        actions:
        - draw teshuhuizhang1_pool
      - op: AND
        children:
        - check: teshuhuizhangbaodijishu < 10
        - check: teshuhuizhang1 == 1
        - check: teshuhuizhang2 == 0
        - check: teshuhuizhang3 == 0
        - check: teshuhuizhang4 == 0
        actions:
        - draw teshuhuizhang2_pool
      - op: AND
        children:
        - check: teshuhuizhangbaodijishu < 10
        - check: teshuhuizhang1 == 1
        - check: teshuhuizhang2 == 1
        - check: teshuhuizhang3 == 0
        - check: teshuhuizhang4 == 0
        actions:
        - draw teshuhuizhang3_pool
      - op: AND
        children:
        - check: teshuhuizhangbaodijishu < 10
        - check: teshuhuizhang1 == 1
        - check: teshuhuizhang2 == 1
        - check: teshuhuizhang3 == 1
        - check: teshuhuizhang4 == 0
        actions:
        - draw teshuhuizhang4_pool
- teshuhuizhangbaodi_execute:
    mode: per_draw
    condition:
      check: teshuhuizhangbaodijishu == 10
      actions:
      - teshuhuizhang1 = 1
      - teshuhuizhang2 = 1
      - teshuhuizhang3 = 1
      - teshuhuizhang4 = 1
      - teshuhuizhangbaodijishu = 0
- teshuhuizhang_execute:
    mode: per_draw
    condition:
      op: AND
      children:
      - check: teshuhuizhang1 == 1
      - check: teshuhuizhang2 == 1
      - check: teshuhuizhang3 == 1
      - check: teshuhuizhang4 == 1
      actions:
      - teshuhuizhang1 = 0
      - teshuhuizhang2 = 0
      - teshuhuizhang3 = 0
      - teshuhuizhang4 = 0
      - teshuhuizhangbaodijishu = 0
      - draw teshuhuizhang_pool
item_resolve:
- item: kai_donghailongwang_aoguang
  retain: 1
  actions:
  - kai_donghailongwang_aoguang -= 1
  - nezha2duihuanbi += 198
- item: miyue_xihailongwang_aorun
  retain: 1
  actions:
  - miyue_xihailongwang_aorun -= 1
  - nezha2duihuanbi += 198
- item: talangtongxintianmu
  retain: 1
  actions:
  - talangtongxintianmu -= 1
  - nezha2duihuanbi += 168
- item: yijianhuiyoutianmu
  retain: 1
  actions:
  - yijianhuiyoutianmu -= 1
  - nezha2duihuanbi += 168
initial:
- change begin_pool
schema_version: 2
every_draw:
- draw_count += 1
