id: wangzhe_zhenpinchuanshuo_nezha2
name: 珍品传说·哪吒2
description: 王者荣耀珍品传说哪吒2活动
terminations:
- file: termination_skin.yaml
  name: termination_skin
- file: termination_skin_33days.yaml
  name: termination_skin_33days
- file: termination_skin_all.yaml
  name: termination_skin_all
- file: termination_tianmu.yaml
  name: termination_tianmu
metadata:
  source: https://pvp.qq.com/web201706/newsdetail.shtml?tid=800320
  game: 王者荣耀
  time: '2026_4_29'
  cost_id: nezha2qiyuanbi
  cost_name: 哪吒2祈愿币
  amount: 6
  per_cost_to_rmb: 1
