retained_items:
- talangtongxintianmu: 1
- nezha2duihuanbi: 428
termination_rule:
  condition:
    op: OR
    children:
    - check: talangtongxintianmu >= 1
      actions: terminate tianmu
    - check: nezha2duihuanbi >= 428
      actions: terminate exchange
