id: sanguosha_xiadanzhonghun
name: 侠胆忠魂
description: 三国杀移动版侠胆忠魂卡池
terminations:
- file: termination_quan1.yaml
  name: termination_quan1
- file: termination_shiweiyan.yaml
  name: termination_shiweiyan
metadata:
  source: https://www.sanguosha.cn/pc/news-detail-2100.html
  game: sanguoshayidonban
  time: '2026_4_25'
  cost_id: xiaddanzhonhun
  cost_name: 侠胆忠魂
  amount: 1
  per_cost_to_rmb: 1
