retained_items:
- shiweiyan: 1
- shishibaozhu_33: 1
termination_rule:
  condition:
    op: OR
    children:
    - check: shiweiyan >= 1
      actions: terminate obtained shiweiyan
    - check: shishibaozhu_33 >= 1
      actions: terminate obtained shishibaozhu_33
